# Generated by Django 4.0.6 on 2022-08-02 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='eta',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='geb',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='height',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='imc',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='weight',
            field=models.FloatField(null=True),
        ),
    ]
